version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o lambdaHandler .

artifacts:
  files:
    - lambdaHandler
    - pokemon.csv